//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForDemo
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Zayavki
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date_add { get; set; }
        public Nullable<System.DateTime> Date_re { get; set; }
        public string Oborud { get; set; }
        public string Type_neis { get; set; }
        public string Disc { get; set; }
        public Nullable<int> Id_Cli { get; set; }
        public Nullable<int> Id_Work { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
    
        public virtual People People { get; set; }
        public virtual People People1 { get; set; }
        public virtual Statuses Statuses { get; set; }

        public int DateAVG
        {
            get
            {
                TimeSpan tiAvg = Date_re.Value - Date_add.Value;
                return Convert.ToInt32(tiAvg.TotalHours);
                
            }
        }
    }
}
